# This is a basic workflow to help you get started with Actions
name: Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      # installe node dans la machine
      - uses: actions/setup-node@v4
        with:
          # installe la version 20 de noteJD
          node-version: 20
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - run: node -v
      - run: pnpm -v

      - run: pnpm install
      - run: pnpm lint
      - run: pnpm test
